### PR TITLE
Add an ability to exclude unnecesarry metrics

### PR DESCRIPTION
**Pull request by ton31337**
With the latest release, we receive a huge amount of unnecessary data:

```
[root@us-imm-log1 ~]# time curl -I 0:9301/metrics
HTTP/1.1 200 OK
Content-Length: 2752967
Content-Type: text/plain; version=0.0.4; charset=utf-8
Date: Fri, 02 Nov 2018 12:39:40 GMT

real	0m20.554s
user	0m0.004s
sys	0m0.006s
```

With this change we can skip metrics we don't need. For instance:

```
EXCLUDE_METRICS=message_bytes_persistent,message_bytes_ram,message_bytes_unacknowledged
```

With huge amount of queues this improves performance 100x when grabbing only necessary metrics.

Exclude list format must be used from here https://www.rabbitmq.com/monitoring.html or from the source code where the mapping is done for each metric.

If this kind of change is acceptable for you then I will update other exporters as well (exchange, node, overview, etc.)

### CODE REVIEW

**Comment by kbudde** [comment]
Hi @ton31337 ,

thank you for the addition. It looks useful.

May I ask you to rename the EXCLUDE_METRICS to SKIP_QUEUE_METRICS as it only applies to queue metrics.

**Comment by ton31337** [comment]
Hey,

I’m planning to use this not only for queues, also for exchange, overview, etc. If that sounds ok for you, I will update rest of exporters.

**Comment by kbudde** [comment]
Hi,

you're welcome to add more changes.

Can you please pull the changes from the v1.0 branch first? 
It is a work in progress. I've renamed some metrics so be carefull.

**Comment by ton31337** [comment]
updated for all exporters

**Comment by ton31337** [comment]
created and rebased on v1.0 https://github.com/kbudde/rabbitmq_exporter/pull/106

**Pull request closed without merging**
