### PR TITLE
Add Windows service support

### PR DESCRIPTION
**Pull request by Teriand**
Basical service start-stop command.

### CODE REVIEW

**Comment by kbudde** [comment]
Hi,

your contribution is welcome but there is still some work todo. 

First it was breaking the build for all other operating systems. I've moved the code for windows in a separate file (see https://github.com/kbudde/rabbitmq_exporter/commit/6b5c0c0d9a895a9c897f3b3fb72951261ebc53d0).
Unfortunately the dependencies are not yet compatible with go modules / one dependency is hosted on sourcegraph where the certificates are failing right now. This should be solved before merging the pr.

Btw. I was running rabbitMQ on windows for some years on windows. If possible try to move to linux it's a better home for the rabbit :)

**Comment by kbudde** [comment]
I'm closing this PR. 
If you want to integrate the windows service support please use the branch https://github.com/kbudde/rabbitmq_exporter/tree/windows-service-support as base.

**Comment by kbudde** [comment]
Hi,

the dependency problem solved itself overnight. Branch was merged. Windows service support is part of the next release.

**Comment by Teriand** [comment]
Ok, thx! Forgot about linux build.
I need run RMQ on windows host as service, yes in enterprise windows12/16 still live.

**Pull request closed without merging**
